### ISSUE TITLE
[Node.js Bootcamp] Project 0: Proxy Server - Ready for Review

### ISSUE THREAD

**Issue by badmonster0** [vanessachem/codpath-proxy-server#1]
My app is complete. /cc @codepathreview @codepath

loglevel and https support are still on my todo list.

**Comment by CrabDude** [comment]
I notice your "hours spent" was only 1 hour. As we work on the scope of the course content and assignments, any feedback is invaluable. How would you describe that hour of work?

For example...
Was it complex, but easy with the walkthrough video?
Was it trivial regardless of the walkthrough video?
Do you feel you learned something?
Were the requirements and/or optionals descriptive enough without the accompanying video?

Thanks in advance! Will follow-up with feedback on your submission.

**Comment by badmonster0** [comment]
@CrabDude  @codepathreview @codepath

For completing the basic requirements, it is pretty straight forward with the walkthrough video. Given i already had system setup and have some understanding about node core concepts.

The through module and create customized logs was something new that i learned.

I would be helpful if "Extending your Server" part to be more descriptive, since there is no tutorial. In terms of requirements on each of the additional bonus item, it would be nice that you can provides some example use case.  So we can understand the question better and complete more efficiently.

**Comment by codepathreview** [comment]
Looks good! Hope you found this first project useful as a brief introduction or review of Node.js.

This was intended in part to give you a flavor for the general rhythm of this course. The course is entirely project based with an app being assigned each week and then due the following week. Each project builds on the last to help each engineer to learn all practical Android development and best practices as quickly as possible. We also do a code review for each submitted project once the bootcamp starts.

The next step is to continue working on extensions to your Node.js server. We will be confirming with you soon if you are going to be a part of the first Node.js bootcamp at Walmart Labs once we determine the location (Sunnyvale or San Bruno). Please email us at nodejs@codepath.com if you have any questions!
