### ISSUE TITLE
through is not acutally writing to the logstream

### ISSUE THREAD

**Issue by badmonster0** [vanessachem/codpath-proxy-server#3]
hey @CrabDude

while i was doing the bonus question, i found the through is not actually working as expect.

It is not closing the file,  but it is actually not writing to the logstream.

I took a look at your video.  it looks like it's not working.

You were piping request to the logstream. 
Your request contains body 'asdf'.
But actually 'asdf' is not if you take a closer look in the terminal.

**Comment by CrabDude** [comment]
Yes. You're right. Good catch!

Instead, do the following:

``` node
// At the top of your file
let logStream = through(null, ()=>{})
logStream.pipe(outputStream)

// In your request handlers, replace `through(source, dest, {autoDestroy: false})` with
source.pipe(logStream)
```

**Comment by CrabDude** [comment]
Turns out there's an even simpler way to do this since core added built-in support for it as a `readable.pipe` option:

``` node
let logStream = argv.log ? fs.createWriteStream(path.join(__dirname, argv.log)) : process.stdout
// ...
req.pipe(logStream, {end: false})
```

I've [updated the Prework](http://courses.codepath.com/snippets/intro_to_nodejs/prework#heading-better-logging) with more explanation and examples.

**Comment by badmonster0** [comment]
@CrabDude thanks adam.
